name: hello-world
on: push
jobs:
  hello-world-jobs:
    runs-on: unbuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
